name: Scale Virtual Machine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  scale:
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure PowerShell Module
        run: Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser

      - name: Import Azure PowerShell Module
        run: Import-Module Az

      - name: Run PowerShell script
        run: |
          $clientId = $env:AZURE_CLIENT_ID
          $clientSecret = $env:AZURE_CLIENT_SECRET
          $tenantId = $env:AZURE_TENANT_ID
          $subscriptionId = $env:AZURE_SUBSCRIPTION_ID
          ./vm-scaling.ps1 -newVmSize 'Standard_B1ms'
        shell: pwsh
