name: Scale Virtual Machine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  scale:
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    steps:
      - name: Set up PowerShell
        uses: actions/setup-powershell@v2
        with:
          pwsh-version: '7.x'

      - name: Run PowerShell script
        run: powershell.exe -File vm-scaling.ps1 -newVmSize 'Standard_B1ms'
