name: Scale Virtual Machine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      newVmSize:
        description: 'New VM Size'
        required: true

jobs:
  scale:
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
      VM_NAME: ${{ vars.VM_NAME }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure PowerShell Module
        run: Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser
        shell: pwsh

      - name: Import Azure PowerShell Module
        run: Import-Module Az
        shell: pwsh

      - name: Run PowerShell script
        run: ./vm-scaling.ps1 -newVmSize ${{ github.event.inputs.newVmSize }}
        shell: pwsh
